const mockData = {
	applicants: [
		{
			applicantId: 1,
			firstName: "Teresa",
			lastName: "NiuB 🐮🍺",
			dateOfBirth: "1999-01-15",
			nationality: "Eldia Empire",
			university: "TUM",
			subject: "IE",
			regularDuration: 4,
			numberOfCredits: 120,
			submissionDate: "2025-01-20",
			submissionTime: "10:30 AM",
		},
		{
			applicantId: 2,
			firstName: "John",
			lastName: "Doe",
			dateOfBirth: "1998-06-20",
			nationality: "Paradise Island",
			university: "TUM",
			subject: "CS",
			regularDuration: 4,
			numberOfCredits: 120,
			submissionDate: "2025-01-21",
			submissionTime: "3:15 PM",
		},
		{
			applicantId: 3,
			firstName: "Seokjin",
			lastName: "Kim",
			dateOfBirth: "1992-12-04",
			nationality: "Korea",
			university: "TUM",
			subject: "CS",
			regularDuration: 4,
			numberOfCredits: 120,
			submissionDate: "2025-02-29",
			submissionTime: "3:15 PM",
		},
	],

	modules: [
		{ moduleId: 1, moduleName: "Informatics", totalCredits: 50 },
		{ moduleId: 2, moduleName: "Theoretical Informatics", totalCredits: 6 },
		{ moduleId: 3, moduleName: "Cyberphysical Systems", totalCredits: 14 },
		{ moduleId: 4, moduleName: "Information Systems", totalCredits: 11 },
		{ moduleId: 5, moduleName: "Mathematics", totalCredits: 30 },
	],

	courses: [
		// Informatics Module
		{
			courseId: 1,
			applicantId: 1,
			moduleId: 1,
			courseName: "Introduction to Informatics",
			achievedCredits: 6,
			totalCredits: 6,
			score: 95,
			deductionRecommendation: 0,
			explanationRecommendation: "No deductions required.",
			courseCode: "INHN0001",
		},
		{
			courseId: 2,
			applicantId: 1,
			moduleId: 1,
			courseName: "Fundamentals of Programming (Exercises & Laboratory)",
			achievedCredits: 6,
			totalCredits: 6,
			score: 85,
			deductionRecommendation: 1,
			explanationRecommendation: "Minor gaps in knowledge.",
			courseCode: "INHN0002",
		},
		{
			courseId: 3,
			applicantId: 1,
			moduleId: 1,
			courseName:
				"Introduction to Computer Organization and Technology - Computer Architecture",
			achievedCredits: 8,
			totalCredits: 8,
			score: 90,
			deductionRecommendation: 0,
			explanationRecommendation: "Well covered.",
			courseCode: "INHN0003",
		},
		{
			courseId: 4,
			applicantId: 1,
			moduleId: 1,
			courseName: "Introduction to Software Engineering",
			achievedCredits: 6,
			totalCredits: 6,
			score: 88,
			deductionRecommendation: 0,
			explanationRecommendation: "Good understanding.",
			courseCode: "INHN0006",
		},
		{
			courseId: 5,
			applicantId: 1,
			moduleId: 1,
			courseName: "Operating Systems and System Software",
			achievedCredits: 6,
			totalCredits: 6,
			score: 80,
			deductionRecommendation: 1,
			explanationRecommendation: "Partial coverage of advanced topics.",
			courseCode: "INHN0007",
		},
		{
			courseId: 6,
			applicantId: 1,
			moduleId: 1,
			courseName: "Fundamentals of Algorithms and Data Structures",
			achievedCredits: 6,
			totalCredits: 6,
			score: 78,
			deductionRecommendation: 1,
			explanationRecommendation: "Some topics not covered.",
			courseCode: "INHN0008",
		},
		{
			courseId: 7,
			applicantId: 1,
			moduleId: 1,
			courseName: "Fundamentals of Databases",
			achievedCredits: 6,
			totalCredits: 6,
			score: 85,
			deductionRecommendation: 0,
			explanationRecommendation: "Good coverage.",
			courseCode: "INHN0011",
		},
		{
			courseId: 8,
			applicantId: 1,
			moduleId: 1,
			courseName: "Computer Networking and IT Security",
			achievedCredits: 6,
			totalCredits: 6,
			score: 82,
			deductionRecommendation: 0,
			explanationRecommendation: "Satisfactory performance.",
			courseCode: "INHN0012",
		},

		// Theoretical Informatics Module
		{
			courseId: 9,
			applicantId: 1,
			moduleId: 2,
			courseName: "Information Theory and Theoretical Informatics",
			achievedCredits: 6,
			totalCredits: 6,
			score: 90,
			deductionRecommendation: 0,
			explanationRecommendation: "Strong theoretical foundation.",
			courseCode: "INHN0013",
		},

		// Cyberphysical Systems Module
		{
			courseId: 10,
			applicantId: 1,
			moduleId: 3,
			courseName: "Introduction to Signal Processing",
			achievedCredits: 6,
			totalCredits: 6,
			score: 75,
			deductionRecommendation: 1,
			explanationRecommendation: "Gaps in applied knowledge.",
			courseCode: "INHN0016",
		},
		{
			courseId: 11,
			applicantId: 1,
			moduleId: 3,
			courseName: "Foundations of Cyber-Physical Systems",
			achievedCredits: 8,
			totalCredits: 8,
			score: 85,
			deductionRecommendation: 0,
			explanationRecommendation: "Well covered.",
			courseCode: "INHN0018",
		},

		// Information Systems Module
		{
			courseId: 12,
			applicantId: 1,
			moduleId: 4,
			courseName:
				"Enterprise Architecture Management and Reference Models",
			achievedCredits: 6,
			totalCredits: 6,
			score: 88,
			deductionRecommendation: 0,
			explanationRecommendation: "Good understanding.",
			courseCode: "INHN0017",
		},
		{
			courseId: 13,
			applicantId: 1,
			moduleId: 4,
			courseName: "Business Process Management",
			achievedCredits: 5,
			totalCredits: 5,
			score: 92,
			deductionRecommendation: 0,
			explanationRecommendation: "Excellent performance.",
			courseCode: "INHN0019",
		},

		// Mathematics Module
		{
			courseId: 14,
			applicantId: 1,
			moduleId: 5,
			courseName: "Discrete Structures",
			achievedCredits: 8,
			totalCredits: 8,
			score: 95,
			deductionRecommendation: 0,
			explanationRecommendation: "Strong understanding.",
			courseCode: "INHN0004",
		},
		{
			courseId: 15,
			applicantId: 1,
			moduleId: 5,
			courseName: "Linear Algebra",
			achievedCredits: 8,
			totalCredits: 8,
			score: 90,
			deductionRecommendation: 0,
			explanationRecommendation: "Well done.",
			courseCode: "INHN0009",
		},
		{
			courseId: 16,
			applicantId: 1,
			moduleId: 5,
			courseName: "Calculus",
			achievedCredits: 8,
			totalCredits: 8,
			score: 85,
			deductionRecommendation: 0,
			explanationRecommendation: "Good understanding.",
			courseCode: "INHN0014",
		},
		{
			courseId: 17,
			applicantId: 1,
			moduleId: 5,
			courseName: "Discrete Probability Theory",
			achievedCredits: 6,
			totalCredits: 6,
			score: 92,
			deductionRecommendation: 0,
			explanationRecommendation: "Strong fundamentals.",
			courseCode: "INHN0020",
		},
		{
			courseId: 1,
			applicantId: 2,
			moduleId: 1,
			courseName: "Introduction to Informatics",
			achievedCredits: 6,
			totalCredits: 6,
			score: 95,
			deductionRecommendation: 0,
			explanationRecommendation: "No deductions required.",
			courseCode: "INHN0001",
		},
		{
			courseId: 2,
			applicantId: 2,
			moduleId: 1,
			courseName: "Fundamentals of Programming (Exercises & Laboratory)",
			achievedCredits: 4,
			totalCredits: 6,
			score: 70,
			deductionRecommendation: 2,
			explanationRecommendation:
				"Missing advanced topics in programming.",
			courseCode: "INHN0002",
		},
		{
			courseId: 3,
			applicantId: 2,
			moduleId: 1,
			courseName: "Operating Systems and System Software",
			achievedCredits: 4,
			totalCredits: 6,
			score: 65,
			deductionRecommendation: 2,
			explanationRecommendation: "Gaps in understanding system software.",
			courseCode: "INHN0007",
		},

		// Theoretical Informatics Module
		{
			courseId: 4,
			applicantId: 2,
			moduleId: 2,
			courseName: "Information Theory and Theoretical Informatics",
			achievedCredits: 3,
			totalCredits: 6,
			score: 50,
			deductionRecommendation: 3,
			explanationRecommendation: "This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation. This is very long recommendation.",
			courseCode: "INHN0013",
		},

		// Cyberphysical Systems Module
		{
			courseId: 5,
			applicantId: 2,
			moduleId: 3,
			courseName: "Introduction to Signal Processing",
			achievedCredits: 6,
			totalCredits: 6,
			score: 75,
			deductionRecommendation: 0,
			explanationRecommendation: "Good coverage of the material.",
			courseCode: "INHN0016",
		},
		{
			courseId: 6,
			applicantId: 2,
			moduleId: 3,
			courseName: "Foundations of Cyber-Physical Systems",
			achievedCredits: 5,
			totalCredits: 8,
			score: 65,
			deductionRecommendation: 3,
			explanationRecommendation:
				"Partial understanding of cyber-physical systems.",
			courseCode: "INHN0018",
		},

		// Information Systems Module
		{
			courseId: 7,
			applicantId: 2,
			moduleId: 4,
			courseName:
				"Enterprise Architecture Management and Reference Models",
			achievedCredits: 6,
			totalCredits: 6,
			score: 88,
			deductionRecommendation: 0,
			explanationRecommendation: "Well understood.",
			courseCode: "INHN0017",
		},
		{
			courseId: 8,
			applicantId: 2,
			moduleId: 4,
			courseName: "Business Process Management",
			achievedCredits: 3,
			totalCredits: 5,
			score: 60,
			deductionRecommendation: 2,
			explanationRecommendation:
				"Partial understanding of process management.",
			courseCode: "INHN0019",
		},

		// Mathematics Module
		{
			courseId: 9,
			applicantId: 2,
			moduleId: 5,
			courseName: "Discrete Structures",
			achievedCredits: 6,
			totalCredits: 8,
			score: 75,
			deductionRecommendation: 2,
			explanationRecommendation: "Missing some key concepts.",
			courseCode: "INHN0004",
		},
		{
			courseId: 10,
			applicantId: 2,
			moduleId: 5,
			courseName: "Linear Algebra",
			achievedCredits: 6,
			totalCredits: 8,
			score: 70,
			deductionRecommendation: 2,
			explanationRecommendation:
				"Gaps in understanding advanced linear algebra.",
			courseCode: "INHN0009",
		},
		{
			courseId: 11,
			applicantId: 2,
			moduleId: 5,
			courseName: "Calculus",
			achievedCredits: 6,
			totalCredits: 8,
			score: 65,
			deductionRecommendation: 2,
			explanationRecommendation: "Partial knowledge of calculus topics.",
			courseCode: "INHN0014",
		},
		{
			courseId: 12,
			applicantId: 2,
			moduleId: 5,
			courseName: "Discrete Probability Theory",
			achievedCredits: 4,
			totalCredits: 6,
			score: 60,
			deductionRecommendation: 2,
			explanationRecommendation:
				"Some concepts are not covered adequately.",
			courseCode: "INHN0020",
		},
	],
};

export default mockData;
